### PR TITLE
Added compile to file example

### PR DESCRIPTION
**Pull request by ryanflorence**
I've been using stitch outside of express apps, thought others might benefit from knowing how to do this as well.

### CODE REVIEW

**Comment by sstephenson** [comment]
Awesome - thanks! (We're using it this way too.)

**Comment by timoxley** [comment]
FYI just created a Stitch command-line utility for writing stitched modules to a file, with optional uglify compression: https://github.com/secoif/StitchUp.

**Comment by sstephenson** [comment]
@secoif, that looks great. Any interest in contributing the command-line tool to Stitch itself?

**Comment by timoxley** [comment]
Sounds good, let's move the discussion to a new issue: https://github.com/sstephenson/stitch/issues/19

**Pull request closed without merging**
