### PR TITLE
Fix double-execution of modules required with differing relative paths.

### PR DESCRIPTION
**Pull request by brandonbloom**
I encountered a bug where two calls to `require` for the same target module, with differing relative paths to that module, resulted in that module's wrapping closure being executed twice. The issue was because cache misses resulted in calling `fn`, even if the module was already in `modules`. This change makes sure the absolute path to any module is always in `cache`.

### CODE REVIEW

**Comment by pangloss** [comment]
I tried this patch out but it did not fix the issue for me. Below I will describe my project structure and how I worked around the problem.

Because I am exporting a "namespace" object rather than a simple class, it is important for me that the root module not be executed twice because otherwise some objects end up being added to the wrong namespace object and not correctly exported.

Here is my original structure:

```
  proj.coffee
  proj/a.coffee
  proj/a/class.coffee
  proj/b.coffee
```

At the top of each file in proj/ I had either `proj = require './proj'` or `proj = require '../proj'`

That didn't work, but I was able to solve the problem with a simple project restructuring, as follows:

```
  proj.coffee
  proj/_actual_root.coffee
  proj/root.coffee
  proj/a.coffee
  proj/a/class.coffee
  proj/b.coffee
```

I moved all code from proj.coffee to proj/_actual_root.coffee, so that is where the root namespace object is created. Then I created proj/root.coffee with just one line:

``` js
module.exports = require './_actual_root'
```

and put the following into proj.coffee:

``` js
module.exports = require './proj/root'
require './proj/a'
require './proj/b'
```

Now in every other file from various relative paths: `proj = require './root'` or `proj = require '../root'`. The proj/root.coffee file is still executed multiple times, but it doesn't matter because proj/_actual_root.coffee is only executed once so all files work with the correct namespace object.

I hope that helps someone, or if anyone has a more elegant solution, I'd love to see it.

Cheers,
Darrick

**Comment by brandonbloom** [comment]
Since posting this patch, I've encountered several other subtle bugs in stitch's current `require` implementation. Besides the original issue this patch fixes, the issue you've outlined above, there is also an issue with the handling of directory index files and in particular, in handling directories which have both an index and a file named matching the index. I encountered this when I tried to do:

```
date_time/index.coffee
date_time/date_time.coffee
date_time/other_stuff.coffee
```

Ultimately, I just gave up trying to fix the Stitch implementation & rewrote the module definition and require path resolution logic myself. Unfortunately, it depends on a bunch of utilities I've written which are deeply intwined with my own project. However, here's the gist of it. Hopefully it's useful:

``` coffee
# Memoizes a module's exports by running initialize (source file body).
load = (module) ->
  return if module.loaded
  {filename} = module
  root = path.dirname(filename)
  require = makeRequire(root)
  try
    module.exports = {}
    module.initialize.call(window, module.exports, require, module)
  catch err
    throw new Error("Error loading '#{filename}': #{err}")
  module.loaded = true
  return

# Returns a require function for use in a given root directory.
makeRequire = (root) -> (name) ->
  filename =
    if name[0] == '.'
      path.join(root, name)
    else
      path.normalize(name)
  module = window.modules[filename]
  unless module
    throw new Error("Cannot find module '#{name}' at '#{filename}'")
  load module
  module.exports

# The global module definition machinery expected by Stitch.
window.require = makeRequire('')
window.require.define = (bundle) ->
  directories = []
  # Create a module for each initialize function in the bundle.
  for filename, initialize of bundle
    window.modules[filename] = {filename, initialize}
    # Note index modules as directories for later.
    if path.basename(filename) == 'index'
      directories.push path.dirname(filename)
  # Reference indexed directories as modules.
  for directory in directories
    if bundle[directory]
      throw new Error("#{directory} matches both a file and a directory")
    window.modules[directory] = window.modules[directory + '/index']
```

**Comment by pangloss** [comment]
Thanks, good to know about the date_time/date_time.coffee issue. I'll avoid it and hopefully won't have to dig further into stitch's internals!

**Comment by boucher** [comment]
Any way we can move this forward?

**Comment by brandonbloom** [comment]
Closing due to lack of interest, personal pull-request cleanup, and other shortcomings of Stitch's require implementation. Feel free to consider my code above in this read public domain, if you wish to incorporate it into Stitch or some other codebase.

**Pull request closed without merging**
